swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /users/{id}/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Ensemble des comptes bancaires de l'utilisateur
      description: Récupérer tous les comptes bancaires appartenant à un utilisateur (Correspond au dashboard (maquette 1))
      parameters:
        - in: path
          name: id
          description: ID de l'utilisateur
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: La récupération des comptes est effective
          schema:
            $ref: '#/definitions/UserAccount'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

  /accounts/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Informations d'un compte bancaire
      description: Récupérer les informations d'un compte bancaire (Se réfère à la partie grise correspondant au compte sélectionné (maquette 2))
      parameters:
        - in: path
          name: id
          description: ID du compte bancaire
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: La récupération du compte sélectionné est effective
          schema:
            $ref: '#/definitions/Accounts'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
  /accounts/{id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Transactions du compte sélectionné filtré par mois
      description: Récupére toutes les transactions d'un compte filtré par mois (Se réfère à la partie verte correspondant à l'ensemble des transactions (maquette 2))
      parameters:
        - in: path
          name: id
          description: ID du compte
          required: true
          type: string
        - in: query
          name: month
          description: Sélectionne le mois désiré
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: La récupération des transactions selon la période désirée est effective
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Non autorisé
        '403':
          description: Interdit
        '404':
          description: Non trouvé
        '500':
          description: Erreur interne du serveur
  /accounts/{id}/transactions{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Mettre à jour une transaction
      description: Permet de modifier las valeurs des propriétés category et note de la transaction (Correspond à la partie verte de la transaction développée (maquette 2)
      parameters:
        - in: path
          name: id
          description: ID de la transaction
          required: true
          type: string
        - in: body
          name: body
          description: Données de la transaction à modifier
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
              note:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Accounts:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      balance:
        type: number
  UserAccount:
    items:
      $ref: '#/definitions/Accounts'
  Transactions:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        amount:
          type: number
        balance:
          type: number
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string
